### ISSUE TITLE
Hello hello

### ISSUE THREAD

**Issue by V1ctorW1ll1an** [Thamyresmya/Controle-Producao#1]
Caracaaa @Thamyresmya que da hora, projeto topzeira, to fazendo um pra apresentar na quinta dessa semana [Motions bee](https://github.com/V1ctorW1ll1an/MotionsBeer), nao sei se vai dar pra voce ver... mas olhei aqui no feed e vi o seu falei "que da hora" kkkk, tem como voce criar discussoes no seu repositorio aqui tmb sabe, ai fica melhor 

🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆

**Comment by Thamyresmya** [comment]
Hei Victor. Obrigada pelas dicas. Estou começando esse projeto agora. Vou fazer junto com uma amiga, porque queremos colocar em prática tudo que já estudando.

**Comment by V1ctorW1ll1an** [comment]
isso ai, vou acompanhar, nao sei mt java mas com certeza vai ficar mt bom
